- hosts: localhost
  become: 'no'
  vars:
    image: ghcr.io/imgios/whaley:1.2.1
  tasks:
    - name: Check if docker is installed on system
      shell: docker --version
      register: version
      failed_when: version.rc != 0
    
    - name: Print docker version
      debug:
        msg: "{{ version.stdout_lines }}"

    - name: Start whaley Kubernetes-in-Docker cluster
      shell: docker run -d --name lab-ops --rm -p 30303:8001 -v /var/run/docker.sock:/var/run/docker.sock -it '{{ image }}'
      register: cluster
      failed_when: cluster.rc != 0
